collective/plone.recipe.varnish

- .travis.yml
- CHANGES.rst
- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/tests/recipe.rst
- plone/recipe/varnish/tests/vclgen.rst
* Some tests were broken after the part split in script, buildout and configuration.
* When testing the recipe I found that /usr/bin/varnishd was always used as location in the start script generation.
* 4.0.3 is now current.
> Fix tests, download Varnish 4.0.3, fix daemon location

- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/tests/recipe.rst
Otherwise, varnishd won't start, with error: "option requires an argument -- 'S'"
> If "secret-file" is "disabled", do not output the "-S" option at all

- CHANGES.rst
- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/tests/recipe.rst
Fix: to disable the secret-file authentication, an empty parameter should be passed to varnishd on startup.
> Fix secret disabled

- .travis.yml
- CHANGES.rst
- README.rst
- plone/recipe/varnish/recipe.py
- 4.0: uses 4.0.3, will stick to 4.0.x
- 4.1: uses 4.1.2, will stick to 4.1.x
- 4: uses 4.1.2, will stick to 4.x.
4 is the default.
> Made three possible values for the ``varnish_version`` option.

- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/templates/varnish4.vcl.jinja2
1) It was missing vcl_backend_response from templating scope
2) fix jinja template when calling custom dictionary keys without quoting its keys. The Result was that any vcl custom injection made in buildout was ignored in template rendering.
> Jinja template fixes

- CHANGES.rst
- plone/recipe/varnish/recipe.py
See https://varnish-cache.org/security/VSV00001.html.
Also updated these urls to not use the repo.varnish-cache.org domain, because those links will stop working at 31 August 2017.
See https://varnish-cache.org/news/index.html#package-repository-status.
> Updated default urls to varnish security releases.

- CHANGES.rst
- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/tests/recipe.rst
For some reason they were renamed after the last release of this recipe.
> Changed default downloads to .tgz instead of .tar.gz.

- .travis.yml
- CHANGES.rst
- README.rst
Travis tests are hanging. I can see from running `bin/createcoverage` locally that it opens the results in the browser. By outputting to the local directory the script exits and travis continues.
I'm not sure if this is then going to affect how coverage.pickle2json and coveralls work - ie: are the results now going anywhere?
> Don't open bin/createcoverage results in browser

- CHANGES.rst
- plone/recipe/varnish/templates/varnish4.vcl.jinja2
This is a PR to resolve issue #42 
Instead of comparing the url to `req.url` compare it to a new variable set on `req.http` which has the query string removed.
> Strip query string before testing which urls to strip cookies on

- .gitignore
- .travis.yml
`VersionConflict: (six 1.11.0 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('six==1.10.0'))`
See for example https://travis-ci.org/collective/plone.recipe.varnish/jobs/311289820
> Fix 'six' problem on Travis

- CHANGES.rst
- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/tests/recipe.rst
- plone/recipe/varnish/tests/test_recipe.py
We used 4.0 until now, because while running the tests with 4.1 Travis kept waiting for input.
Let's see if that got magically fixed.
If it works now, we may have more hope of getting varnish 5 working too.
> Use 4.1 version by default (4.0 was default until now).

- CHANGES.rst
- plone/recipe/varnish/recipe.py
Without this change I'have this error (varnish 4.1):
```
Error:
Message from VCC-compiler:
Expected ID got ';'
(program line 166), at
('.../parts/varnish-config/varnish.vcl' Line 265 Pos 27)
set beresp.grace = 600;
--------------------------#
Running VCC-compiler failed, exited with 2
VCL compilation failed
```
> fix grace-sick default

- CHANGES.rst
- README.rst
- base.cfg
- plone/recipe/varnish/recipe.py
- travis.cfg
It was defined in the varnish vcl templates but never picked up.
> Pick up vcl_hash custom code insertion again from the buildout recipe values

- CHANGES.rst
- plone/recipe/varnish/recipe.py
I see this actually partially overlaps with PR #67 but that one is a bit older so it updates to 4.1.10 instead. That PR should be revisited afterwards, as it had a Travis failure.
> Updated default varnish 4 version to latest 4.1.11.

- .travis.yml
- CHANGES.rst
- base.cfg
- bootstrap-4.3.x.sh
- bootstrap-5.0.x.sh
- bootstrap.sh
- plone-4.3.x.cfg
- plone-5.0.x.cfg
- travis.cfg
See issue #69.
- `buildout.cfg` now extends `base.cfg` and `versions.cfg`.
- `travis.cfg` by default extends both but has a slightly different code-analysis setup. The different setup may not make sense anymore, but that is how it was until now. code-analysis passes with both setups.
- In `.travis.yml` we do one run with standard `travis.cfg`, and one allowed failure with `travis.cfg` minus the `versions.cfg`. We could skip that and have just one job.
So if we don't mind further simplification/unification then there is some room, and I can do that. But we can also merge as is, when Travis passes.
> Simplified test buildout setup by not using plone versions.

- base.cfg
I though I had run it locally, but apparently not in the right way.
Travis complains about lots of lines with 'C812 missing trailing comma'.
Running 'black' fixes only a few of them, so I don't want to bother at this point.
So ignore C812 for now.
Also, running 'black' would give this error, which in the future will no longer be an error:
W503 line break before binary operator
So ignore that one too.
> Fix Travis code-analysis.

- .travis.yml
- CHANGES.rst
- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/tests/recipe.rst
Update versions 6 and 6.0 to latest version 6.0.4 Anything below 6.0.X is officially unmaintained from varnish-cache.org
Set default version to version 6, downloading 6.0.4 if no url is provided.
Fix double env assignment in travis.yml
Disable building sphinx documentation in the varnish-build/cmmi stage of installing the software.
> Update Varnish versions. Small fixes in versioning & tests

- CHANGES.rst
- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/templates/varnish4.vcl.jinja2
- plone/recipe/varnish/templates/varnish5.vcl.jinja2
- plone/recipe/varnish/templates/varnish6.vcl.jinja2
- plone/recipe/varnish/vclgen.py
When using the load-balancing feature of Varnish, the configuration created with this recipe configures Varnish to request the front-page of the Plone site.
With this change a new option is added to the recipe to let the user configure the URL he wants and defaulting it to [Plone's `/ok` view](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/okay.py).
@libargutxi @aitzol
> Add an option to modify the health-check url defaulting to Plone's /ok view

- README.rst
previously these options have been documented in the script section but
they are only handled in `plone.recipe.varnish:configuration`
(fixes #20)
> move grace-* options to configuraition section

- CHANGES.rst
- plone/recipe/varnish/vclgen.py
just noticed that i introduced a regression when moving the defaults from `recipe` to `vlcgen` - sorry about that @fredvd...
a bugfix release would be welcome as users not providing a probeurl and using grace-health will always have sick backends and varnish not responding to any requests.
> bugfix: omitting healthprobeurl resulted in "None"

- CHANGES.rst
- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/templates/start_script.jinja2
- plone/recipe/varnish/tests/recipe.rst
I don’t know why, but the secret file path is modified to lowercase in the recipe. This is a problem, for example,  if there are capitals in the buildout path.
> secret filename case sensitive

- CHANGES.rst
- plone/recipe/varnish/templates/start_script.jinja2
- plone/recipe/varnish/tests/recipe.rst
Allow to configure storages other than file and malloc (i.e. umem and default)
BTW, probably nowadays the best default storage would be `default` instead of `file`.
https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html
> allow to use the other storages

- CHANGES.rst
- bootstrap.sh
- plone/recipe/varnish/recipe.py
- setup.py
Afterwards, we should do a release.  Some bug fixes have been done.
This package can use some more love, probably starting with issue #90.  But that can wait until after a release.
> Use Varnish 6.0.11 LTS.

- CHANGES.rst
- README.rst
- plone/recipe/varnish/recipe.py
- plone/recipe/varnish/templates/varnish6.vcl.jinja2
- plone/recipe/varnish/tests/vclgen.rst
- plone/recipe/varnish/vclgen.py
``cookie-pass-not-exclude``
If url matches this regexp, ``cookie-pass`` exclude rules are skipped. This is useful
for url like ``++resource++zmi`` that requires authentication also for resources
like js, css, ...
> Add `cookie-pass-not-exclude` config
